### ISSUE TITLE
Cache file read failure

### ISSUE THREAD

**Issue by ZeltaDred** [shundhammer/qdirstat#22] opened 2016-08-09 16:59 UTC
Program fails to read/load complete  cache  file..

Environment is Ubuntu 16.04 VM ( virtualbox ) with QT 5.7 ( opensource )
Cache file  attached..
[qdirstat.cache.gz](https://github.com/shundhammer/qdirstat/files/409488/qdirstat.cache.gz)

File generated by pointing at  root (/) mount point while  running as non-root  user.
Treemap builds and displays,  Cache file save seems  to write "correct" information.

When attempting to read the cache file,  the first (/) directory and the 2 file links are the only things processed / displayed..

Log file  is full of the "cannot find  parent" messages referenced in the other cache file issue reported

[qdirstat-1000.log.tar.gz](https://github.com/shundhammer/qdirstat/files/409504/qdirstat-1000.log.tar.gz)

**Comment by shundhammer** [comment] 2016-08-10 13:26
I can reproduce the problem with the attached cache file.

Thanks for reporting this! Will investigate.

**Comment by shundhammer** [comment] 2016-08-10 16:46
Looks like that old parser was a bit too simplistic for some fringe cases. This should be fixed now. There is some performance impact, though: Unlike previously, we now have a regexp search & replace for each cache line to avoid double slashes (which QUrl doesn't seem to handle well).

**Closed by shundhammer** 2016-08-10 16:46 UTC
Labels: bug

**Comment by ZeltaDred** [comment] 2016-08-10 18:07
Looks like the regexp replace is overstepping its intent..


screen  view  prior  to cache  save...
![screenshot from 2016-08-10 11-52-59](https://cloud.githubusercontent.com/assets/20263588/17565017/d84fbd9a-5ef2-11e6-9e44-5d4d415603ff.png)


after  cache file read...
![screenshot from 2016-08-10 11-53-55](https://cloud.githubusercontent.com/assets/20263588/17565046/f36e4c5e-5ef2-11e6-824a-3f9666aaad28.png)

the cache file was generated  the same way as  originally  reported

**Comment by shundhammer** [comment] 2016-08-11 13:28
I was unsure about this for a while, but I can now reproduce it.

This is unrelated to this original issue, though: This is a problem in the internal cache writer class. When I generate the cache file with the supplied qdirstat-cache-writer script, I get the exact same result (7.8 GB total) for my root file system no matter if qdirstat reads it directly from disk or if it reads the cache file.

When I generate that cache file with the "File" -> "Write Cache File" menu actions, though, the resulting cache file contains only 457 MB worth of files.

I will clone this into a separate issue to keep track of this.

**Comment by shundhammer** [comment] 2016-08-11 13:32
Cloned issue: https://github.com/shundhammer/qdirstat/issues/23
