### ISSUE TITLE
l10n: Program Translations

### ISSUE THREAD

**Issue by jose1711** [shundhammer/qdirstat#188] opened 2022-02-19 15:45 UTC
Please add support for more languages as currently the program only speaks English.

**Comment by shundhammer** [comment] 2022-02-20 12:15
The QDirStat source code is prepared to handle translations: User-visible texts are using Qt's `tr()` function (inherited from `QObject`) in the `*.cpp` and in the `*.ui` files; that works very much like GNU _gettext_. What is missing is a mechanism to load a translation file upon program start.

And then comes all the rest, and that's why I am _very_ reluctant to do that:

- Set up and use some web service (_Weblate_?) to make the texts available to volunteer translators.

- Collect the results (the translated tests) to make them them ready for packaging.

- Do some quality control which languages are translated to an extent to make it worthwhile to distribute them to end users: How many percent of the messages are translated, how many are marked as _fuzzy_ or completely untranslated?

- Package them / make them available for distribution package maintainers.

**Comment by jose1711** [comment] 2022-02-20 12:25
Thank you.

> * Set up and use some web service (Weblate?) to make the texts available to volunteer translators.
> * Collect the results (the translated tests) to make them them ready for packaging.

How about skipping the "translation service" part for now and only accept PRs with `.ts` added/updated? I've seen couple projects working like this relying on translators themselves rather than an external service.

> * Do some quality control which languages are translated to an extent to make it worthwhile to distribute them to end users: How many percent of the messages are translated, how many are marked as fuzzy or completely untranslated?

Perhaps this could be done only at release time: i. e. not so often.

> * Package them / make them available for distribution package maintainers.

But this should be the responsibility of the maintainers, right? Or did you mean adding them to the project and making sure the translations are converted to `.qm` and installed during `make install`?

**Comment by shundhammer** [comment] 2022-02-20 12:25
For the predecessor project, _KDirStat_ (the KDE 1 / 2 / 3 version), over time, some few volunteers had trickled in to make a translation for their native language. I had made translations for my native German; somebody provided a French translation, somebody else a Japanese, and I think there were one or two others as well.

The problem is: That does not scale, and bit-rot sets in pretty quickly. This is not a one-time effort, it's continuous ongoing work; as the program evolves, as bugs are fixed, as new features are added, there are always some new user-visible messages, and existing ones change ever so slightly; even if just a typo is fixed, the corresponding translation does not match anymore, and translation tools mark such a message as _fuzzy_, meaning "please have a look at it and check if the translation is still correct". If nobody does that and removes that _fuzzy_ marker, the translation is no longer used, and the original message from the program sources (English by convention) is used instead. So you get a mixture of translated and untranslated messages on the screen; some in your native language, some in English. That's a mess.

So those one-time translations that those volunteers had contributed deteriorated more and more over time, making that whole program translation thing of more and more questionable value. While I could (and did) maintain the German translation, I didn't even know just how bad those other translations had become; if they were still worthwhile to be distributed, or if users of those languages would be better off with the honest solution: Not pretending to provide translations for languages that were not really maintained, but rather removing those translations.

**Comment by shundhammer** [comment] 2022-02-20 12:35
So, as honorable the intentions of single volunteers to translate program messages are, in my experience that doesn't work out on the long run. The only viable way IMHO is using a project that is supported by many volunteer translators, not just one; something like _Weblate_.

But as I have seen in my day job at SUSE, that comes with its own problems. Many of those volunteer translators take great pride to provide all kinds of software with translations to their language, and that's a good thing; but of course, since they are volunteers, they are doing that on their own schedule, not necessarily at a release schedule of  the Open Source software.

As a result, commits for translations keep coming in all the time; some translators translate large numbers of messages at once, some do it little by little; the results are trickling in all the time in dozens or hundreds of individual Git commits.

Having those in the same repository as the program code results in a giant mess; it's completely impossible to see source code changes between the sheer mass of those translation changes. The Git history deteriorates to the point of total uselessness.

So the only viable approach that I see is moving that out into a separate Git repo; something like, say, _qdirstat-lang_ that would contain the translation-related things.

An automated build logic would be required to extract the messages from the QDirStat source code repository and upload them to _Weblate_ (or whatever other translation service would be chosen), to collect the translations from there and to (pre-) package them so they could be made available by distro packagers as a separate _qdirstat-lang_ package (in _.deb_, _.rpm_ or whatever format).

**Comment by shundhammer** [comment] 2022-02-20 12:53
While this is all doable, even if it's quite some work, this begs he question: Is this really worth the hassle?

Over the last few releases, I had added lots and lots of features to QDirStat, but I never received _any_ kind of feedback, negative or positive:

https://github.com/shundhammer/qdirstat/blob/master/README.md#history

In particular, the additional views were lots of work that I thought would contribute to the overall usefulness of the program:

- The _Details_ panel at the right side
- Showing what software package (if any) a system file belongs to
- The _File Type_ (by filename extensions) view
- The _File Size Distribution Histogram_ view
- The _Packages_ view
- The _Unpackaged Files_ view
- The _File Age_ view
- The _Mounted Filesystems_ (`df` like) view

Are users so happy with those that there is nothing to talk or complain about? Or isn't anybody using any of that in the first place?

While I keep seeing tons of low-quality articles on the web about QDirStat, they never explore the program beyond the most basic functionality, and they typically only explain how to install it (because that's a pretty primitive copy & paste of existing text from other articles). That begs the question if normal users ever get beyond those basics.

Going through the hassle of providing translations would be adding more stuff where I really wonder if it's worth the investment of work, time and life energy.

**Comment by shundhammer** [comment] 2022-02-20 12:58
My thoughts about translations in an older (in the meantime removed) _TODO.md_ document:

https://github.com/shundhammer/qdirstat/blob/stable-1.6/doc/TODO.md#translations

**Comment by shundhammer** [comment] 2022-02-20 13:04
About relying on individual translators for specific languages:

- I could contribute a native German translation.
- I could probably persuade one of my Czech colleagues at work to contribute a Czech translation (our main SUSE offices are in Nürnberg and Prague).
- I could probably also persuade ony of my Spanish colleagues on the Canary islands to contribute Spanish.
- Maybe I could get one of my Russian colleagues to contribute a Russian translation.
- I guess you would like to contribute Slovak.

While that's a start, it leaves great gaps. That's where a larger Open Source project like _Weblate_ could come in; they have lots more people with lots more languages.

**Comment by jose1711** [comment] 2022-02-20 13:05
> Over the last few releases, I had added lots and lots of features to QDirStat, but I never received any kind of feedback, negative or positive.

Maybe this is a more profound problem. I've been using Linux since 2002 and it's only recently that I found your project (and I must say - I like it a lot). Also perhaps another problem may be that people don't look for programs like yours on a daily basis. Often they try to solve this only if the OS starts reporting a low disk space and they decide not to invest in a new drive.

**Comment by jose1711** [comment] 2022-02-20 13:07
>     * I guess you would like to contribute Slovak.

Yes, that is correct. I do this for many programs/projects that I find useful.

**Comment by shundhammer** [comment] 2022-02-20 13:21
Let me think about all this for a while.

I don't want to make any promises here and now. But this topic has been on the agenda ever since I started the QDirStat project; i.e. since after I took my old KDE 3 KDirStat and ripped out the KDE parts out of sheer frustration (see section "Motivation / Rant" in the project toplevel README.md).

Maybe (just maybe!) I'll start a test balloon so the program will pick up and use translation files if any are found, so the part of the source code is covered; then it would be a matter of putting translation files into suitable locations, however they would get there (from a separate _qdirstat-lang_ package? Dropped as a gift / Pandora's box from heaven?).

Adding just the infrastructure for that in the code shouldn't be too hard to do.

And adding that check box '[x] Use Translations' to the "General" tab in the config dialog, of course, so I can escape my own self-created hell of translated-to-death software, of course. ;-)

**Comment by shundhammer** [comment] 2022-04-15 17:30
It's been two months now. I thought about this many times, and I feel zero motivation to open this can of worms; it's not only the mechanism to load translations, it's also the hassle and the constant maintenance.

I have seen so many projects where the translations keep rotting away all the time; this depends on the project's size, the amount of people behind it, the number of volunteer translators, and how active they are over time. Also, it's not possible for a small number of people in the project to assess the quality of translations for any language they don't actively speak; it's even hard for those that they do speak.

Sorry to disappoint you, but the decision here is to better not do this at all.

**Closed by shundhammer** 2022-04-15 17:30 UTC
Labels: feature request

**Comment by jose1711** [comment] 2022-04-15 19:09
Thank you, got it.
