### ISSUE TITLE
Why the non-conforming icon set?

### ISSUE THREAD

**Issue by endigma-4426** [shundhammer/qdirstat#150] opened 2021-01-14 18:47 UTC
In-app icons are not system themed, they appear to be some derivative of humanity but not sure, def not the ones I have set.

**Comment by shundhammer** [comment] 2021-01-15 00:22
This is a duplicate of https://github.com/shundhammer/qdirstat/issues/44 .
The same arguments as back then are still valid.

**Closed by shundhammer** 2021-01-15 00:22 UTC
