### ISSUE TITLE
incorrect handling of sparse files with 0 allocated blocks

### ISSUE THREAD

**Issue by oliver** [shundhammer/qdirstat#10] opened 2016-02-02 13:21 UTC
If a file has 0 allocated blocks but has a logical size which is greater than 0, the file will not be detected as "sparse"; instead, their logical size will be used as actual size.

To create such a file, run eg. `dd if=/dev/zero of=test.bin bs=1M seek=1000 count=0`; this creates a sparse file which uses 0 blocks of space but has a logical size of 1000 MB. Qdirstat displays a misleading size of 1000 MB for this file.
If you run `dd if=/dev/zero of=test.bin bs=1M seek=1000 count=1` instead, the file uses 2048 blocks and has a logical size of 1001 MB. For this file, qdirstat correctly shows a size of "1001 MB (allocated: 1.0 MB)".

This was observed on an ext4 file system, with latest qdirstat (f33cba3a43dc30d53da8b9bdc5a22922e830282a).
The issue does not occur with k4dirstat 2.7.8-4-ge61717f.

**Comment by shundhammer** [comment] 2016-02-03 14:18
Hm - I can see where this comes from, and "git blame" also told me when:

https://github.com/shundhammer/kdirstat/blob/master/kdirstat/kfileinfo.cpp#L83

	_isSparseFile	= isFile()
	    && _blocks > 0				// if file system can't report blocks
	    && allocatedSize() + FRAGMENT_SIZE < _size;	// allow for intelligent fragment handling

    df8eeed5 (Stefan Hundhammer 2006-02-05 18:31:45 +0000  82)      _isSparseFile   = isFile()
    df8eeed5 (Stefan Hundhammer 2006-02-05 18:31:45 +0000  83)          && _blocks > 0                              // if file system can't report blocks
    df8eeed5 (Stefan Hundhammer 2006-02-05 18:31:45 +0000  84)          && allocatedSize() + FRAGMENT_SIZE < _size; // allow for intelligent fragment handling

This might have been after k4dirstat was forked off.

I have some vague memories that I had introduced this to avoid getting a zillion bogus sparse files on certain file systems - maybe FAT / VFAT. Let me check if that still applies today.

**Comment by shundhammer** [comment] 2016-02-03 15:06
Fixed with https://github.com/shundhammer/qdirstat/commit/b7e89787b007a12998a9e2517d1ed61d7b7df7e9 .

I couldn't reproduce that old problem that made me restrict sparse file detection to files with at least one block, but I'd rather not reintroduce that problem. Thus, the famous German overengineering to the front: ;-)

Now keeping track if any block size > 0 was ever detected in the directory tree, and only if it was, this means that the file system does report block sizes, so sparse file detection is enabled in that tree.

This is not 100% fool proof in more than one aspect, but it should work reasonably well in real world use cases. The pathological cases are:

- If reading across file system boundaries is enabled (or if the user selects "continue reading at mount point"), the new DirTree::fileSystemCanReportBlocks() function will return 'true' for any file in that directory tree, even if a file system is mounted there that really cannot report blocks. This might lead to false positives, i.e. sparse files getting reported on file systems that don't really return that information.

- Some file systems like Btrfs report some directories as having 0 blocks, and if you scan a directory tree with just such a directory at toplevel and then a sparse file with 0 blocks as the first file, this might also not get detected as a sparse file. But this is a pretty contrived pathological case with little real world relevance IMHO.

**Comment by oliver** [comment] 2016-02-04 13:38
The fix works fine when using qdirstat directly. But it doesn't work when using a cache file, since qdirstat-cache-writer doesn't use the same algorithm that you implemented in DirTree.cpp.

For testing I changed qdirstat-cache-writer to _always_ write the amount of blocks used, and that fixed the problem. So maybe that would actually be a good solution?
This hack also highlighted another issue: even if a file is just 20 bytes, it will actually occupy 4 KB of disk space, but qdirstat will show that it uses just 20 bytes of disk space. This is probably not a technical question but a question of semantics. But interestingly the `du` tool also counts the amount of occupied _blocks_, not the logical file size.

**Comment by shundhammer** [comment] 2016-02-04 16:40
Hm - right, the qdirstat-cache-writer part is missing. It will probably be enough to write a nonzero block size once in the tree, because that's already the sign that the file system can report blocks sizes.

Reopening for the qdirstat-cache-writer part.

As for block sizes vs. byte sizes, this is a conceptual problem: This is handled differently in different types of file systems. Some actually use a full block for such "fragments", others have special blocks reserved for them, others might put them into meta data blocks up to a certain size. It's not only very small files, it's also for the last part of a file that doesn't quite fill a disk block.

And of course, none of them discloses that information. There is no syscall that might return it. I can only speculate that "du" has a list of file system types and their respective strategies and does some rule-of-thumb calculation based on that. Or maybe its results are completely bogus - you'll never know. ;-)

**Comment by shundhammer** [comment] 2016-02-05 12:58
OK, reverted that previous fix, took a step back and found a way without overengineering - actually just replacing the initial "> 0" with ">= 0".

I had intended to extend the DirCacheReader to use blocks -1 if unknown and calculate it based on the standard block size (512 bytes) in that case so it doesn't get zero when reading a cache file.

Then I looked at the code and found I had already had that same thought 10 years ago when I introduced that feature - it was already there. The difference is just that it's not the DirCacheReader that does that calculation, but the FileInfo class itself, so it's even more generic.

And since I couldn't find any more file system type today that does not return the size in blocks, there is no more need to be overcautious against that; but OTOH there is no more need for that overengineering that sometimes fails in pathological cases. Now it should simply always work.

**Closed by shundhammer** 2016-02-05 12:58 UTC
Labels: bug
