### ISSUE TITLE
[Feature/nitpick] An option to use current icon theme instead of the built-in one.

### ISSUE THREAD

**Issue by jedenastka** [shundhammer/qdirstat#148] opened 2020-11-19 12:17 UTC
QDirStat is a good tool. There is nothing that is missing for me.

But I have a little nitpick... it always uses it's own icon theme. A music player that I use (Strawberry) also has it's own icons, but there is an option to use the current icon theme. I realize that I see *much* more of my music player than I see of QDirStat, but it just upsets me a little bit every time I use it.

If it's already there, sorry for wasting your time.
If you don't want it added, fine, I'll suffer :]

**Comment by shundhammer** [comment] 2020-11-19 15:44
This is a duplicate of https://github.com/shundhammer/qdirstat/issues/44 .
The same arguments as back then are still valid.

**Closed by shundhammer** 2020-11-19 15:44 UTC
