### ISSUE TITLE
Integrate the file stats and directories with the main window

### ISSUE THREAD

**Issue by C0rn3j** [shundhammer/qdirstat#51] opened 2017-02-20 20:03 UTC
How I imagine this to look/be positioned - http://i.imgur.com/e77oD7R.png

I think this would be a great default option with the ability to resize all 3 windows and be able to pop them out so they act like they currently do for people who'd like to use them as such

With the way it currently is it feels cluttery on a lower than FHD res screen, and I'd like this even on my FHD screen(currently using lower res TV).

- Being tracked here  too #52 

---

Also when the directory listing pops out it ignores the last position it was at, it'd be great if it opened at the last position.

- Fixed! Thanks!
---
And as a small side note - it is great to open the file stats menu by F3, would be even better if it worked as toggle and F3 also closed it if it is open.

- Implemented, thanks!

---
And Thank You so much for implementing the file stats feature and making it even better by adding file listings, it makes it so much more useable for me and the listing of files by directories makes it even better than WinDirStat, especially the synergy between all 3 windows is very cool!.

**Comment by shundhammer** [comment] 2017-02-20 20:25
Yes, saving and restoring the window sizes and preferably also their (relative) positions is indeed still an open issue.

**Comment by C0rn3j** [comment] 2017-02-20 20:37
Was that meant literally? I can only see 2 other issues and neither are about window positioning

**Comment by shundhammer** [comment] 2017-02-20 20:39
No, not literally GitHub issues. Just in general.

**Comment by shundhammer** [comment] 2017-02-20 20:40
OK, F3 is now an app-wide toggle. 

Making it app-wide was the tricky part; normally, QAction shortcuts are limited to their window, i.e. when the file type stats window was opened, it would receive that F3 keypress, don't know how to handle it, and silently discard it.

**Comment by C0rn3j** [comment] 2017-02-20 21:01
Thanks a bunch! 

There's a small bug with it though - when you press F3 quickly, QDirStat loses focus. Seems like it doesn't happen when you wait for the File stats menu to load and then close it, maybe not accepting F3 as input until the window loads/closes would fix that?

**Comment by shundhammer** [comment] 2017-02-20 21:03
See also https://github.com/shundhammer/qdirstat/issues/52

**Comment by shundhammer** [comment] 2017-02-20 21:07
> There's a small bug with it though - when you press F3 quickly, QDirStat loses focus. 

It might be a matter of event sequence - it uses deleteLater() on the file type stats window when it is already open. deleteLater(), as the name implies, happens sometime _later_ - when there is nothing to do in the event loop. But when there is another F3 press, it might try to recreate it already before deleteLater() is executed.

Will investigate.

> Seems like it doesn't happen when you wait for the File stats menu to load and then close it, maybe not accepting F3 as input until the window loads/closes would fix that?

That's not so easy; that stuff is handled deep down inside Qt. It handles those QAction shortcuts deep in internal event handlers.

**Comment by shundhammer** [comment] 2017-02-21 11:15
> Yes, saving and restoring the window sizes and preferably also their (relative) positions is indeed still an open issue.

Fixed with https://github.com/shundhammer/qdirstat/commit/efaf7af77dc95c59dcee6959892ed809b1f25c3f

**Comment by shundhammer** [comment] 2017-02-21 11:21
> How I imagine this to look/be positioned - http://i.imgur.com/e77oD7R.png

This is going too far for in the direction of a WinDirStat lookalike contest. 

I don't want that File Type Stats window/panel to obscur any information of the tree view. I might go for extending the window to the right and to the bottom for the benefit of those two other windows, but I want QDirStat to retain an uncluttered user interface. I don't want everybody and his mother spread screenshots on the web showcasing all the "cool stuff" you can also dump into the main window, thereby scaring off sane users who want a clear user interface. I've seen that too often. 

For some time, some company tried to make me work with _Enterprise Architect_ where they had put that to extremes with dozens of panels and sub-panels and stuff cluttering the main window. When I tried to enter it to the "User Interface Hall of Shame" I found that others had already put it there long ago. I don't want QDirStat to be even considered for that contest. 😃

**Comment by C0rn3j** [comment] 2017-02-21 11:49
Personally I'd prefer the docking, but if that is too cluttery in your opinion, then I'd at least suggest docking File stats and Dir listing together like so.
![image](https://cloud.githubusercontent.com/assets/1641362/23163623/6fe48224-f833-11e6-866c-2aceacf9a89e.png)

---

Small bug with remembering the window positions - Trying to open the <No Extension> files just closes the Directory listing UI and when being opened back the position is reset.

---

Also do you think that a locate button/double clicking is needed? Seems like listing your 30k images took 200ms, and based on that I think it'd be better if the button was removed and simply selecting an entry would list the directory, 
and perhaps it could be possible to deselect the entry, making the Directories window close again if user opened it by accident?

**Comment by shundhammer** [comment] 2017-02-21 12:56
> Small bug with remembering the window positions - Trying to open the files just closes the Directory listing UI and when being opened back the position is reset.

I can't reproduce that.

**Comment by shundhammer** [comment] 2017-02-21 12:58
> Also do you think that a locate button/double clicking is needed? Seems like listing your 30k images took 200ms, and based on that I think it'd be better if the button was removed and simply selecting an entry would list the directory,

No. That would be too intrusive. Not everybody who, for example, uses the cursor keys to navigate through the tree necessarily wants to open the "Locate" window and shuffle around tree branches in the main window at the same time.

Not to mention the fact that people do accept a short delay for an operation that they think (as they should) take some time, but is actually quite fast; but if that happens for every keypress, even 100 milliseconds feel sluggish.

**Comment by shundhammer** [comment] 2017-02-21 13:01
> and perhaps it could be possible to deselect the entry, making the Directories window close again if user opened it by accident?

If people double-click "by accident", there _should_ be a learning process involved to make them think about what they are doing just a little bit. And clicking on that "Close" button is not exactly rocket science (and you could even just leave it open).

**Comment by shundhammer** [comment] 2017-02-21 13:03
> I'd at least suggest docking File stats and Dir listing together like so.

No way. They are independent for a good reason: Once you found the file type you are interested in, you can simply close the "file type stats" window and continue working just with the "Locate results" window and the main window. The "stats" window tends to be too much in the way at that point. And screen real estate is the limiting factor here.

**Comment by shundhammer** [comment] 2017-02-21 13:06
>  when you press F3 quickly, QDirStat loses focus.

I can't reproduce this, no matter how hard I try, both on Kubuntu 14.04 with Qt 5.4 (?) or on openSUSE Tumbleweed with Qt 5.7.

**Comment by C0rn3j** [comment] 2017-02-21 13:57
>I can't reproduce this, no matter how hard I try, both on Kubuntu 14.04 with Qt 5.4 (?) or on openSUSE Tumbleweed with Qt 5.7.

You need to do it quickly but not too quickly, crappy video with a ton of artifacting(because I didn't figure out how to make OBS capture of whole screen nonarticating yet...)

I'm on Qt 5.8 using Arch.

https://www.youtube.com/watch?v=vJE8_9bn9a8&feature=youtu.be

>I can't reproduce that.

It happens 100% of the time for me, maybe it's the Qt version bump? What should happen when you try to open the <No Extensions> file?

EDIT: After opening qdirstat through a terminal once, I never got it to happen again. Whether I was opening it through the terminal or through my DE(Cinnamon)

**Comment by shundhammer** [comment] 2017-02-21 15:18
If it happens only when dealing with large directory trees, by all means **have some patience** and don't wildly bang on the F3 key while calculations are ongoing. Just think about the extensive computations going on there and how you disrupt them with impatiently switching the window on and off because 200 milliseconds are already too long.

**Comment by shundhammer** [comment] 2017-02-23 16:38
If this happens (which I am not sure yet) it will be as part of issue #52 .

Since this issue is pretty cluttered already, closing this in favour of #52.

**Closed by shundhammer** 2017-02-23 16:38 UTC
