### ISSUE TITLE
Characters not accepted in folder names

### ISSUE THREAD

**Issue by LucMorizur** [shundhammer/qdirstat#38] opened 2016-12-02 21:29 UTC
Hi;

many thanks for QDirStat :-) !

as shown in attached screenshot, using special characters, as "À" for example, is not accepted :-/ .

Thanks again!

--
_Luc_

![document](https://cloud.githubusercontent.com/assets/24322102/20851064/6f436892-b8de-11e6-9152-b9ce6f25c5eb.jpg)

**Comment by shundhammer** [comment] 2016-12-04 21:17
I am pretty sure that this is a duplicate of https://github.com/shundhammer/qdirstat/issues/19 : File/directory names not encode in UTF-8. And the same explanations as in that issue apply here, too.

You can test this in a shell window: Go to that directory `/home/luc/Photos/Tri photos/Photos` and check what the `ls` command shows you. Then check your locale environment with the `locale` command. If it shows an UTF-8 environment (like `fr_FR.UTF-8`), the characters will look like in QDirStat. If it's `fr_FR.latin1` or `fr_FR.iso-8859-1`, the characters will probably look correct.

As explained in detail in that issue#19, Linux distributions went to great lengths for a long time to fix all those locale problems, and there is only one real fix: Migrate to UTF-8 - because that can display all special characters for all languages. That's what all the major distros did.

That does not change any existing file or directory names, of course; but there are tools that can do that for you.

**Closed** 2016-12-04 21:22 UTC
Labels: duplicate

**Comment by shundhammer** [comment] 2016-12-09 12:31
Luc, any news on this? Can you confirm that this is indeed a duplicate?

**Comment by shundhammer** [comment] 2017-05-31 20:18
Luc, it turns out you were right all along: There was a problem with QDirStat built against Qt 4.x (which is what NHellFire's PPA does). See issue #61 which is now fixed.
