### ISSUE TITLE
Underline in Details panel is not showing

### ISSUE THREAD

**Issue by stdedos** [shundhammer/qdirstat#121] opened 2020-02-19 17:36 UTC
Expected: ![https://raw.githubusercontent.com/shundhammer/qdirstat/master/screenshots/QDirStat-byte-size-2a.png](https://raw.githubusercontent.com/shundhammer/qdirstat/master/screenshots/QDirStat-byte-size-2a.png)

Actual:
![image](https://user-images.githubusercontent.com/133706/74859132-1a7ad200-534f-11ea-8431-de8cb7ddb346.png)

**Comment by shundhammer** [comment] 2020-02-20 09:01
What widget theme are you using? What Qt version?

**Comment by shundhammer** [comment] 2020-02-20 13:14
If you are using Qt 4.x, this cannot work: `QWidget::QEnterEvent()` and `QWidget::QLeaveEvent()` are supported only from Qt 5.0 on. Previously (with Qt 4.x) you'd had to go through contortions to override `QObject::QEvent()` completely and then query the event type for `QEvent::Enter` and `QEvent::Leave`.

**Comment by shundhammer** [comment] 2020-02-20 13:49
Please build this branch:

https://github.com/shundhammer/qdirstat/tree/huha-debug-enter-leave

Then follow the log (`tail -F /tmp/qdirstat-$USER/qdirstat.log`) while moving the mouse cursor into and out of that size widget. You should see messages like this:

```
2020-02-20 14:48:31.643 [5731] <Debug>   FileSizeLabel.cpp:96 enterEvent():  entering FileSizeLabel 127.1 MB
2020-02-20 14:48:34.723 [5731] <Debug>   FileSizeLabel.cpp:114 leaveEvent():  leaving FileSizeLabel 127.1 MB
```

**Comment by shundhammer** [comment] 2020-02-22 12:15
Still waiting for feedback.

**Comment by stdedos** [comment] 2020-02-23 18:38
Apologies, weekends are usually off for me. I hope that's understandable.

1. I'm using qt 5, on Ubuntu Xenial, and I don't know what widget theme I'm using (GTK+?)
![image](https://user-images.githubusercontent.com/133706/75117487-72307a80-567a-11ea-9cfd-614decfef628.png)

(_Could you add a short, copyable "Version Info" on Help>About or somewhere there with this basic info?_)

2. Only the underline is not showing, the click produces the byte size context menu

3. Here is the log:

```
2020-02-23 20:19:26.357 [4561] <Info>    Logger.cpp:143 openLogFile():  -- Log Start --
2020-02-23 20:19:26.357 [4561] <Info>    main.cpp:58 logVersion():  QDirStat-1.6.1 built with Qt 5.5.1
2020-02-23 20:19:26.618 [4561] <WARNING> [Qt] void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "" under id 46
2020-02-23 20:19:26.623 [4561] <Debug>   DebugHelpers.cpp:133 dumpExcludeRules():  <ExcludeRule ".snapshot">
2020-02-23 20:19:26.624 [4561] <Debug>   DirTreeModel.cpp:635 sort():  Sorting by NameCol ascending
2020-02-23 20:19:26.624 [4561] <Debug>   TreemapView.cpp:123 setSelectionModel():  
2020-02-23 20:19:26.625 [4561] <Info>    Cleanup.cpp:415 desktopSpecificApps():  Detected desktop "Unity"
2020-02-23 20:19:26.625 [4561] <Info>    Cleanup.cpp:468 desktopSpecificApps():  %filemanager => "nautilus"
2020-02-23 20:19:26.625 [4561] <Info>    Cleanup.cpp:468 desktopSpecificApps():  %terminal => "gnome-terminal &"
2020-02-23 20:19:26.625 [4561] <Debug>   MainWindow.cpp:1256 changeLayout():  Changing to layout L2
2020-02-23 20:19:26.628 [4561] <Info>    PkgQuery.cpp:66 checkPkgManagers():  Checking available supported package managers...
2020-02-23 20:19:26.628 [4561] <Debug>   SysUtil.cpp:97 runCommand():  /usr/bin/dpkg -S /usr/bin/dpkg
2020-02-23 20:19:26.806 [4561] <Info>    PkgQuery.cpp:95 checkPkgManager():  Found primary package manager dpkg
2020-02-23 20:19:26.806 [4561] <Info>    SysUtil.cpp:83 runCommand():  Command not found: /bin/rpm
2020-02-23 20:19:26.806 [4561] <Info>    SysUtil.cpp:83 runCommand():  Command not found: /usr/bin/pacman
2020-02-23 20:19:26.806 [4561] <Info>    PkgQuery.cpp:84 checkPkgManagers():  Found dpkg
2020-02-23 20:19:26.806 [4561] <Info>    MainWindow.cpp:1349 toggleVerboseSelection():  Verbose selection is now off. Change this with Shift-F7.
2020-02-23 20:19:30.927 [4561] <Debug>   DirTree.cpp:480 setExcludeRules():  Clearing tmp exclude rules
2020-02-23 20:19:30.927 [4561] <Info>    DirTree.cpp:121 startReading():     url: "/home/user/workspace"
2020-02-23 20:19:30.927 [4561] <Info>    DirTree.cpp:124 startReading():  device: /home/user/.Private
2020-02-23 20:19:30.928 [4561] <Debug>   MainWindow.cpp:965 expandTreeToLevel():  Expanding tree to level 1
2020-02-23 20:19:31.055 [4561] <Info>    MainWindow.cpp:657 readingFinished():  
2020-02-23 20:19:31.056 [4561] <Debug>   DirTreeModel.cpp:635 sort():  Sorting by PercentNumCol descending
2020-02-23 20:19:31.056 [4561] <Debug>   MainWindow.cpp:639 idleDisplay():  No current branch - expanding tree to level 1
2020-02-23 20:19:31.056 [4561] <Debug>   MainWindow.cpp:965 expandTreeToLevel():  Expanding tree to level 1
2020-02-23 20:19:31.062 [4561] <Info>    MainWindow.cpp:663 readingFinished():  Reading finished after 0.129 sec
2020-02-23 20:19:31.128 [4561] <Debug>   MainWindow.cpp:965 expandTreeToLevel():  Expanding tree to level 1
2020-02-23 20:19:32.193 [4561] <Debug>   FileSizeLabel.cpp:96 enterEvent():  entering FileSizeLabel 2.5 MB
2020-02-23 20:19:33.377 [4561] <Debug>   FileSizeLabel.cpp:114 leaveEvent():  leaving FileSizeLabel 2.5 MB
2020-02-23 20:19:34.857 [4561] <Debug>   FileSizeLabel.cpp:96 enterEvent():  entering FileSizeLabel 2.5 MB
2020-02-23 20:19:35.274 [4561] <Debug>   FileSizeLabel.cpp:114 leaveEvent():  leaving FileSizeLabel 2.5 MB
2020-02-23 20:23:11.817 [4561] <Debug>   DirTree.cpp:480 setExcludeRules():  Clearing tmp exclude rules
2020-02-23 20:23:11.817 [4561] <Info>    DirTree.cpp:121 startReading():     url: "/tmp/FoxitReaderlite"
2020-02-23 20:23:11.817 [4561] <Info>    DirTree.cpp:124 startReading():  device: /dev/mapper/work--group-Ubuntu_16.04_Secondary
2020-02-23 20:23:11.817 [4561] <Debug>   DirTreeModel.cpp:635 sort():  Sorting by NameCol ascending
2020-02-23 20:23:11.817 [4561] <Debug>   MainWindow.cpp:965 expandTreeToLevel():  Expanding tree to level 1
2020-02-23 20:23:11.850 [4561] <Info>    MainWindow.cpp:657 readingFinished():  
2020-02-23 20:23:11.850 [4561] <Debug>   DirTreeModel.cpp:635 sort():  Sorting by PercentNumCol descending
2020-02-23 20:23:11.850 [4561] <Debug>   MainWindow.cpp:639 idleDisplay():  No current branch - expanding tree to level 1
2020-02-23 20:23:11.850 [4561] <Debug>   MainWindow.cpp:965 expandTreeToLevel():  Expanding tree to level 1
2020-02-23 20:23:11.885 [4561] <Info>    MainWindow.cpp:663 readingFinished():  Reading finished after 0.034 sec
2020-02-23 20:23:12.018 [4561] <Debug>   MainWindow.cpp:965 expandTreeToLevel():  Expanding tree to level 1
2020-02-23 20:24:58.547 [4561] <Debug>   FileSizeLabel.cpp:96 enterEvent():  entering FileSizeLabel 4.1 kB
2020-02-23 20:24:58.995 [4561] <Debug>   FileSizeLabel.cpp:114 leaveEvent():  leaving FileSizeLabel 4.1 kB
```

Are those temporary diagnostics? Maybe they should be added on master, e.g. when starting `qdirstat -v`, toggleable via Settings>Configure>Logging, ... ?

**Comment by shundhammer** [comment] 2020-02-23 18:59
Ubuntu 16.04 Xenial Xerus uses the Unity desktop which uses the Gtk widget theme by default (unless you reconfigured that).

I had a problem with that widget theme just lately while working on YaST; it looks to me like that widget theme uses real Gtk widgets internally for rendering widget content, and sometimes it simply ignores widget attributes like color and uses the Gtk widget's default instead. It is entirely possible that it also just ignores setting the "underline" attribute.

**Comment by shundhammer** [comment] 2020-02-23 19:07
So, the problem is purely cosmetic (albeit annoying); the functionality is still there.

**Comment by shundhammer** [comment] 2020-02-23 19:25
You can force Qt to use a different widget theme; but then of course Qt applications look differently than the Gtk applications that your desktop normally uses.

To do that, install the `qt5ct` package and start the `qt5ct` application:

```
sudo apt-get install qt5ct
export QT_QPA_PLATFORMTHEME=qt5ct
qt5ct
```
![qt5ct](https://user-images.githubusercontent.com/11538225/75118390-03ebb800-567a-11ea-9696-1168137329fd.png)

Select a widget style there (_Style: Fusion_ in this example) and apply your changes.
Then start QDirStat again and test. I bet now you can see the underlines.

To make the changes permanent (if you wish to do that), add this to your shell environment, typically in `~/.bashrc`:

```
export QT_QPA_PLATFORMTHEME=qt5ct
```

See also

https://askubuntu.com/questions/910012/how-can-i-get-qt5-applications-to-use-the-gtk-theme-in-ubuntu-17-04  (not sure how much that applies to Xenial)

**Comment by shundhammer** [comment] 2020-02-23 19:26
> Are those temporary diagnostics?

No, that's just debug logging. It's not useful to have that in _master_.

**Comment by shundhammer** [comment] 2020-02-23 19:38
This might be the same problem or at least a very similar one like this:

https://bugzilla.suse.com/show_bug.cgi?id=1162241#c8

I installed `adwaita-qt`and switched to the _Adwaita_ theme with `qt5ct`, but I get the underlines just fine (using Xubuntu 18.04 LTS Bionic Beaver with Qt 5.9.5).

At work, I use openSUSE Tumbleweed with Qt 5.14 (the latest one) and also the _Fusion_ theme for Qt, and it works there fine as well (otherwise I would not have released this at all, of course).

It is also possible that this is only a bug in that rather old Qt 5.5 that comes witn Xenial; Qt 5.5 was released in 2012. There might have been any number of fixes in the 8 years since then.

**Comment by shundhammer** [comment] 2020-02-23 19:43
Summary:

- This is a cosmetic problem. Though annoying, it does not change the functionality.

- There is a workaround: Select another widget theme with `qt5ct` (see above).

- The problem is upstream in either the Qt Gtk widget theme or (less likely) in the Qt libs; this is beyond the control of QDirStat.

So, the problem and the workaround are now documented; this is all that can be done here.

Closing.

**Closed by shundhammer** 2020-02-23 19:43 UTC

**Comment by stdedos** [comment] 2020-02-24 10:14
So much response :wow: Let's break it down:

> So, the problem is purely cosmetic (albeit annoying); the functionality is still there.

Can you mark / enhance the functionality for "those broken" distributions?
e.g. Make the cursor a "href-clicker"?

I understand if you want to go there, though

> You can force Qt to use a different widget theme; but then of course Qt applications look differently than the Gtk applications that your desktop normally uses.
> 
> To do that, install the `qt5ct` package and start the `qt5ct` application:

Xenial some machinery to keep going:

`sudo add-apt-repository ppa:nilarimogard/webupd8`

However, yes, whatever option I may pick from here, it seems that it works (and yes it slightly alters "native" look&feel)

> This might be the same problem or at least a very similar one like this:
> 
> https://bugzilla.suse.com/show_bug.cgi?id=1162241#c8
> 
> I installed `adwaita-qt`and switched to the _Adwaita_ theme with `qt5ct`, but I get the underlines just fine (using Xubuntu 18.04 LTS Bionic Beaver with Qt 5.9.5).
> 
> At work, I use openSUSE Tumbleweed with Qt 5.14 (the latest one) and also the _Fusion_ theme for Qt, and it works there fine as well (otherwise I would not have released this at all, of course).
> 
> It is also possible that this is only a bug in that rather old Qt 5.5 that comes with Ubuntu Xenial; that Qt 5.5 was released in 2015. There might have been any number of fixes in the 5 years since then.

I've found the Qt backport PPAs here https://launchpad.net/~beineri and picked the latest

```console
$ sudo add-apt-repository -y ppa:beineri/opt-qt-5.14.1-xenial
$ sudo apt-get update
$ sudo apt-get install -y qt514-meta-minimal
$ . /opt/qt514/bin/qt514-env.sh
$ qmake
$ make && sudo make install
$ qdirstat
```

and/or changing the `.desktop` file

```patch
-Exec=qdirstat %f
+Exec=bash -c '. /opt/qt514/bin/qt514-env.sh ; qdirstat %f'
```

works; and this preserves look&feel.

Would you document that at least?

**Comment by shundhammer** [comment] 2020-02-24 11:22
Well, it is now documented; here in the issue tracker. :smiley:

**Comment by shundhammer** [comment] 2020-02-24 11:23
Let me think about the mouse cursor. You may have got an idea here.

**Comment by shundhammer** [comment] 2020-02-24 12:12
Not sure if it's only on my Xfce desktop, but those other cursors all look dead ugly and not anything like in the Qt reference documentation:

https://doc.qt.io/qt-5/qcursor.html#details

I tried `Qt::PointingHandCursor` which should come closest semantically (they write it's for clickable objects like hyperlinks) and `Qt::WhatsThisCursor` which doesn't really quite fit. Both look absolutely ugly on my machine; they don't look like they are coming from a modern cursor theme, but from some ancient X11 cursor font.

**Comment by stdedos** [comment] 2020-02-24 12:16
Well, if you cannot "reasonably" fix it, then forget it.

I agree that the cursors look ugly; idk why Qt cannot "ask" the OS to show the cursor, falling back to its own if unable.
